name: Everhunt
version: '${project.version}'
main: me.nils.everhunt.Everhunt
api-version: '1.20'
commands:
  item:
  spawn:
  warp:
  market:
  sell:
  achievement:
  guild:
  report:
  reports:
  job: